UPDATE IPL..MATCHES
SET WINNER = 'Rising Pune Supergiant'
WHERE WINNER = 'Rising Pune Supergiants'

UPDATE IPL..MATCHES
SET TEAM1 = 'Rising Pune Supergiant'
WHERE TEAM1 = 'Rising Pune Supergiants'

UPDATE IPL..MATCHES
SET TEAM2 = 'Rising Pune Supergiant'
WHERE TEAM2 = 'Rising Pune Supergiants'

UPDATE IPL..MATCHES
SET VENUE = 'Punjab Cricket Association Stadium, Mohali'
WHERE VENUE ='Punjab Cricket Association IS Bindra Stadium, Mohali'

--NUMBER OF MATCHES IN EACH VENUE

SELECT VENUE, COUNT(VENUE)
FROM IPL..MATCHES
GROUP BY VENUE 
ORDER BY VENUE

--WINS BY EACH TEAM BY VENUE

SELECT DISTINCT VENUE, WINNER, COUNT(VENUE) AS WINS_IN_VENUE
FROM IPL..MATCHES
GROUP BY VENUE, WINNER
ORDER BY VENUE

--NUMBER OF MATCHES WHERE THE TOSS WINNER IS THE WINNER BY VENUE

SELECT DISTINCT VENUE, COUNT(VENUE) AS WINS
FROM IPL..MATCHES
WHERE TOSS_WINNER = WINNER
GROUP BY VENUE
ORDER BY VENUE

--NUMBER OF MATCHES WHERE THE TOSS WINNER IS THE WINNER IN EACH VENUE BY TEAM

SELECT DISTINCT VENUE, TOSS_WINNER, WINNER, COUNT(VENUE) AS WINS
FROM IPL..MATCHES
WHERE TOSS_WINNER = WINNER
GROUP BY VENUE, TOSS_WINNER, WINNER
ORDER BY VENUE

--NUMBER OF MATCHES WHERE THE TOSS WINNER IS THE WINNER BY TOSS DECISION IN EACH VENUE

SELECT DISTINCT VENUE,TOSS_DECISION, COUNT(VENUE) AS WINS
FROM IPL..MATCHES
WHERE TOSS_WINNER = WINNER
GROUP BY VENUE, TOSS_DECISION
ORDER BY VENUE

-- TOP 10 PLAYERS WITH THE MOST PLAYER OF THE MATCH AWARD

SELECT TOP 10 PLAYER_OF_MATCH, COUNT(PLAYER_OF_MATCH) AS NUMBER_OF_TIMES
FROM IPL..MATCHES
GROUP BY PLAYER_OF_MATCH
ORDER BY NUMBER_OF_TIMES DESC

-- TOP 10 PLAYERS WITH THE MOST PLAYER OF THE MATCH AWARD BY VENUE

SELECT TOP 10 PLAYER_OF_MATCH, COUNT(PLAYER_OF_MATCH) AS NUMBER_OF_TIMES, VENUE
FROM IPL..MATCHES
GROUP BY PLAYER_OF_MATCH, VENUE
ORDER BY NUMBER_OF_TIMES DESC, PLAYER_OF_MATCH, VENUE

--TOP 10 MATCHES WITH THE MOST RUN DIFFERENCE

SELECT TOP 10 TEAM1, TEAM2, TOSS_WINNER, TOSS_DECISION, WINNER, RESULT_MARGIN, VENUE
FROM IPL..MATCHES
WHERE RESULT = 'RUNS'
ORDER BY RESULT_MARGIN DESC

--TOP 10 MATCHES WITH THE MOST RUN DIFFERENCE WHERE THE TOSS WINNER IS THE WINNER

SELECT TOP 10 TEAM1, TEAM2, TOSS_WINNER, TOSS_DECISION, WINNER, RESULT_MARGIN, VENUE, DATE
FROM IPL..MATCHES
WHERE RESULT = 'RUNS' AND TOSS_WINNER = WINNER
ORDER BY RESULT_MARGIN DESC

-- TOSS DECISION BASED ON THE VENUE

SELECT VENUE, TOSS_DECISION, COUNT(TOSS_DECISION) AS TIMES
FROM IPL..MATCHES
GROUP BY VENUE, TOSS_DECISION
ORDER BY VENUE

--TEMP TABLE
DROP TABLE IF EXISTS #VENUEBASED
CREATE TABLE #VENUEBASED
(VENUE NVARCHAR(255),
TOSS_WINNER NVARCHAR(255),
TOSS_DECISION NVARCHAR(255),
WINNER NVARCHAR(255),
RESULT NVARCHAR(255),
RESULT_MARGIN FLOAT,
MATCHESBYVENUE FLOAT)

INSERT INTO #VENUEBASED
SELECT VENUE, TOSS_WINNER, TOSS_DECISION, WINNER, RESULT, RESULT_MARGIN, COUNT(VENUE) OVER (PARTITION BY VENUE) AS MATCHESBYVENUE
FROM IPL..MATCHES

-- PERCENTAGE OF MATCHES WHERE THE TOSS WINNING TEAM WINS THE MATCH BY VENUE

SELECT DISTINCT VENUE, COUNT(VENUE) AS WINS, MATCHESBYVENUE, (COUNT(VENUE)/MATCHESBYVENUE)*100 AS PERCENTAGEOFWIN
FROM #VENUEBASED
WHERE TOSS_WINNER = WINNER
GROUP BY VENUE, MATCHESBYVENUE
ORDER BY VENUE

-- TOSS DECISION BY VENUE PERCENTAGE

SELECT DISTINCT VENUE,TOSS_DECISION, COUNT(VENUE) AS TIMES_CHOSEN, MATCHESBYVENUE, COUNT(VENUE)/MATCHESBYVENUE*100 AS PERCENTAGE
FROM #VENUEBASED
GROUP BY VENUE, TOSS_DECISION, MATCHESBYVENUE
ORDER BY VENUE

--WINNING TOSS DECISION BY VENUE PERCENTAGE

SELECT DISTINCT VENUE,TOSS_DECISION, COUNT(VENUE) AS TIMES_CHOSEN, MATCHESBYVENUE, COUNT(VENUE)/MATCHESBYVENUE*100 AS PERCENTAGE
FROM #VENUEBASED
WHERE TOSS_WINNER = WINNER
GROUP BY VENUE, TOSS_DECISION, MATCHESBYVENUE
ORDER BY VENUE

--TEAMS WITH THE MOST WINS BY VENUE

SELECT TOP 10 VENUE, WINNER, COUNT(VENUE) AS WINS_IN_VENUE,MATCHESBYVENUE, COUNT(VENUE)/MATCHESBYVENUE *100 AS PERCENTAGE
FROM #VENUEBASED
GROUP BY VENUE, WINNER, MATCHESBYVENUE
ORDER BY PERCENTAGE DESC
